"""description of migration

Revision ID: 444c55f4d42c
Revises: 22fe3db8aba8
Create Date: 2024-08-04 10:36:46.093276

"""
from alembic import op
from ckanext.showcase.data.constants import ApprovalStatus
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '444c55f4d42c'
down_revision = '22fe3db8aba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('showcase_approval',
    sa.Column('showcase_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column(
        'status',
        sa.types.Enum(ApprovalStatus, name="showcase_status_enum"), 
        nullable=False, 
        default=ApprovalStatus.PENDING
        ),
    sa.ForeignKeyConstraint(['showcase_id'], ['package.id'], name='showcase_approval_showcase_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('showcase_id', name='showcase_approval_pkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('showcase_approval')

    # ### end Alembic commands ###
