"""Date added in Approval table

Revision ID: 87bec6583583
Revises: 09f4781de341
Create Date: 2024-08-04 10:57:45.897601

"""
import datetime
from alembic import op
from ckanext.showcase.data.constants import ApprovalStatus
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '87bec6583583'
down_revision = '09f4781de341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('showcase_approval', sa.Column('status_modified', sa.types.DateTime, nullable=True, default=datetime.datetime.utcnow))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ckanext_issues', 'status_modified')
